spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: update

  data:
    redis:
      port: 6379
      host: localhost

  jwt:
    secret: linker
    token:
      access-expiration-time: 86400000    # 24시간
      refresh-expiration-time: 604800000  # 7일

server:
  tomcat:
    remoteip:
      remote-ip-header: "x-forwarded-for"
      protocol-header: "x-forwarded-proto"