server:
  tomcat:
    remoteip:
      remote-ip-header: "x-forwarded-for"
      protocol-header: "x-forwarded-proto"
spring:
  web:
    resources:
      add-mappings: false
  profiles:
    active: local
  config:
    import:
        - logging.yml
        - monitoring.yml
        - application-oauth.yml
        - application-storage-${spring.profiles.active}.yml
springdoc:
  swagger-ui:
    path: /swagger
  use-fqn: true

jwt:
  access-token-properties:
    secret: ${JWT_ACCESS_TOKEN_SECRET}
    expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
  refresh-token-properties:
    secret: ${JWT_REFRESH_TOKEN_SECRET}
    expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME}