database:
  encryption:
      enable: false
      key: 1234567890123456
      iv: 1234567890123456
spring:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true