database:
  encryption:
    enable: false
    key: 1234567890123456
    iv: 1234567890123456
spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
