database:
  encryption:
      enable: false
      key: 1234567890123456
      iv: 1234567890123456
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        query:
          in_clause_parameter_padding: true
          plan_cache_max_size: 128
          plan_parameter_metadata_max_size: 32
    open-in-view: false

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug